# DEBUG = -O0 -g

TOPDIR = ../..
LIBS = -lalgcomm 

OBJS = quickfinduf.o quickunionuf.o \
	weightedquickunionuf.o unionfind.o
SLIBS = libunionfind.a
CLIB = -lunionfind
EXECS = qfuf quuf wquuf uf

.include "$(TOPDIR)/algcode.mk"
