# DEBUG = -Og -g

TOPDIR = ../..
LIBS = -lheap -llinearlist -lbinaryio -lalgcomm -lm

OBJS = runlength.o huffman.o lempelzivwelch.o
SLIBS = libalgstrings.a
CLIB = -lalgstrings
EXECS = genome runlen hfm lzw

.include "$(TOPDIR)/algcode.mk"
