# DEBUG = -O0 -g

TOPDIR = ..
LIBS = -lseqsearch -llinearlist -lalgcomm
OBJS = separatechainhash.o lineprobhash.o
SLIBS = libhash.a
CLIB = -lhash
EXECS = schash lphash

.include "$(TOPDIR)/algcode.mk"
